var $ = require('jquery');
window.jQuery = $;
window.$ = $;
require('bootstrap');
require('jquery.easing');
require('../freelancer.min.js');
require('../status.js');
require('../githubContributors.js');
require('../starred.js');
require('../lastUpdated.js');
